name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm # or pnpm or yarn
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Install JS dependencies
        run: npm ci # or pnpm nstall / yarn install / bun install
      - name: Build Pelican site
        run: |
          pelican \
            --settings "pelicanconf.py" \
            --extra-settings SITEURL='"${{ steps.pages.outputs.base_url }}"' \
            --output "output/"
      - name: Fix permissions
        run: |
          chmod -c -R +rX "output/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: output/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
